import React from 'react';

interface InvoiceData {
  bookingId: string;
  customerName: string;
  customerPhone: string;
  customerEmail?: string;
  vehicleName: string;
  vehicleModel?: string;
  licensePlate?: string;
  driverName?: string;
  driverPhone?: string;
  bookingType: string;
  pricingType?: string;
  pickupLocation: string;
  dropoffLocation: string;
  pickupDate: string;
  returnDate: string;
  pickupTime: string;
  returnTime: string;
  totalDays?: number;
  totalKilometers?: number;
  baseAmount: number;
  tollCharges?: number;
  parkingCharges?: number;
  miscellaneousAmount?: number;
  miscellaneousDescription?: string;
  totalAmount: number;
  invoiceDate: string;
  pricePerDay?: number;
  pricePerKm?: number;
}

interface InvoiceTemplateProps {
  data: InvoiceData;
  className?: string;
}

export const InvoiceTemplate: React.FC<InvoiceTemplateProps> = ({ data, className = "" }) => {
  const formatCurrency = (amount: number) => `₹${amount.toLocaleString()}`;
  
  return (
    <div className={`bg-white p-8 max-w-4xl mx-auto ${className}`} id="invoice-template">
      {/* Header */}
      <div className="flex justify-between items-start mb-8 border-b-2 border-gray-300 pb-6">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-4">MGROWW FleetPro</h1>
          <div className="text-sm text-gray-600 space-y-1">
            <div><strong>Website:</strong> www.mgroww.com</div>
            <div><strong>Email:</strong> mgroww@gmail.com</div>
            <div><strong>GSTIN:</strong> 777786820</div>
          </div>
        </div>
        <div className="text-right">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">INVOICE</h2>
          <div className="text-sm text-gray-600 space-y-1">
            <div><strong>Date:</strong> {data.invoiceDate}</div>
            <div><strong>Generated by:</strong> FleetPro System</div>
          </div>
        </div>
      </div>

      {/* Customer and Booking Details */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        {/* Customer Details */}
        <div>
          <h3 className="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">Customer Details</h3>
          <div className="space-y-2 text-sm">
            <div><strong>Name:</strong> {data.customerName}</div>
            <div><strong>Phone Number:</strong> {data.customerPhone}</div>
            {data.customerEmail && (
              <div><strong>Email:</strong> {data.customerEmail}</div>
            )}
            <div><strong>Booking ID:</strong> {data.bookingId}</div>
          </div>
        </div>

        {/* Booking Summary */}
        <div>
          <h3 className="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">Booking Summary</h3>
          <div className="space-y-2 text-sm">
            <div><strong>Booking Type:</strong> {data.bookingType.replace('_', ' ')}</div>
            <div><strong>Vehicle:</strong> {data.vehicleName} {data.vehicleModel || ''}</div>
            {data.licensePlate && (
              <div><strong>License Plate:</strong> {data.licensePlate}</div>
            )}
            {data.driverName && (
              <div>
                <strong>Driver:</strong> {data.driverName}
                {data.driverPhone && ` - ${data.driverPhone}`}
              </div>
            )}
            <div><strong>From:</strong> {data.pickupLocation}</div>
            <div><strong>To:</strong> {data.dropoffLocation}</div>
            <div><strong>Pickup:</strong> {data.pickupDate} at {data.pickupTime}</div>
            <div><strong>Return:</strong> {data.returnDate} at {data.returnTime}</div>
          </div>
        </div>
      </div>

      {/* Fare Summary Table */}
      <div className="mb-8">
        <h3 className="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">Fare Summary</h3>
        <table className="w-full border border-gray-300">
          <thead>
            <tr className="bg-gray-50">
              <th className="border border-gray-300 px-4 py-2 text-left text-sm font-semibold">Item</th>
              <th className="border border-gray-300 px-4 py-2 text-left text-sm font-semibold">Description</th>
              <th className="border border-gray-300 px-4 py-2 text-right text-sm font-semibold">Amount (INR)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border border-gray-300 px-4 py-2 text-sm">Vehicle Rent</td>
              <td className="border border-gray-300 px-4 py-2 text-sm">
                {data.pricingType === 'km' ? (
                  <>
                    {data.totalKilometers} KM @ {formatCurrency(data.pricePerKm || 0)}/km
                  </>
                ) : (
                  <>
                    {data.totalDays} Day(s) {data.vehicleName} {data.vehicleModel || ''}
                  </>
                )}
              </td>
              <td className="border border-gray-300 px-4 py-2 text-right text-sm">{formatCurrency(data.baseAmount)}</td>
            </tr>
            
            {data.driverName && (
              <tr>
                <td className="border border-gray-300 px-4 py-2 text-sm">Driver Charges</td>
                <td className="border border-gray-300 px-4 py-2 text-sm">{data.driverName}</td>
                <td className="border border-gray-300 px-4 py-2 text-right text-sm">Included</td>
              </tr>
            )}

            {data.tollCharges && data.tollCharges > 0 && (
              <tr>
                <td className="border border-gray-300 px-4 py-2 text-sm">Toll Charges</td>
                <td className="border border-gray-300 px-4 py-2 text-sm">Highway tolls and taxes</td>
                <td className="border border-gray-300 px-4 py-2 text-right text-sm">{formatCurrency(data.tollCharges)}</td>
              </tr>
            )}

            {data.parkingCharges && data.parkingCharges > 0 && (
              <tr>
                <td className="border border-gray-300 px-4 py-2 text-sm">Parking Charges</td>
                <td className="border border-gray-300 px-4 py-2 text-sm">Parking fees and charges</td>
                <td className="border border-gray-300 px-4 py-2 text-right text-sm">{formatCurrency(data.parkingCharges)}</td>
              </tr>
            )}

            {data.miscellaneousAmount && data.miscellaneousAmount > 0 && (
              <tr>
                <td className="border border-gray-300 px-4 py-2 text-sm">Miscellaneous Expenses</td>
                <td className="border border-gray-300 px-4 py-2 text-sm">{data.miscellaneousDescription || 'Additional charges'}</td>
                <td className="border border-gray-300 px-4 py-2 text-right text-sm">{formatCurrency(data.miscellaneousAmount)}</td>
              </tr>
            )}

            <tr className="bg-gray-50 font-semibold">
              <td className="border border-gray-300 px-4 py-2 text-sm" colSpan={2}>Total</td>
              <td className="border border-gray-300 px-4 py-2 text-right text-sm">{formatCurrency(data.totalAmount)}</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Notes Section */}
      <div className="mb-8">
        <h3 className="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">Notes</h3>
        <div className="text-sm text-gray-700 space-y-2">
          <div>1. Please carry a valid ID proof during travel.</div>
          <div>2. Payment must be completed before journey starts.</div>
          <div>3. For support, contact mgroww@gmail.com or call 7777888220.</div>
        </div>
      </div>

      {/* Footer */}
      <div className="border-t-2 border-gray-300 pt-6">
        <div className="text-center mb-4">
          <p className="text-sm font-medium text-gray-800">Thank you for choosing MGroww FleetPro.</p>
        </div>
        <div className="text-center">
          <p className="text-xs text-gray-600">This is a system-generated invoice and does not require signature.</p>
        </div>
      </div>
    </div>
  );
};

export default InvoiceTemplate;