/**
 * ProviderConnection Model
 * Tenant-scoped connections to third-party providers
 * Enforces multi-tenant isolation and credential encryption
 */

import mongoose, { Schema, Document } from 'mongoose';
import { ProviderConnectionStatus, ProviderConfig, EncryptedCredentials } from '../types';

/**
 * ProviderConnection Interface
 * One connection per tenant per provider
 */
export interface IProviderConnection extends Document {
  // Reference to IntegrationProvider
  providerId: string;

  // Multi-tenant isolation - which tenant owns this connection
  tenantId: mongoose.Types.ObjectId;

  // User who created/manages this connection
  createdBy: string;

  // Display name for this connection (e.g., "Main WhatsApp Business")
  displayName: string;

  // Connection status
  status: ProviderConnectionStatus;

  // Encrypted credentials
  credentials: EncryptedCredentials;

  // Decrypted config (stored securely, never returned to client)
  config: ProviderConfig;

  // Connection metadata
  metadata?: {
    // Provider-specific account identifier (e.g., phone number for WhatsApp)
    accountId?: string;

    // Account name/description
    accountName?: string;

    // Additional metadata
    [key: string]: any;
  };

  // Last authentication success
  lastAuthenticatedAt?: Date;

  // Last authentication failure
  lastAuthFailureAt?: Date;

  // Consecutive failure count
  failureCount: number;

  // Maximum allowed failures before disabling
  maxFailureThreshold?: number;

  // When connection will be auto-disabled
  disabledUntil?: Date;

  // Connection usage statistics
  stats?: {
    totalRequests: number;
    totalErrors: number;
    averageResponseTime?: number;
    lastUsedAt?: Date;
    quotaUsed?: number;
    quotaLimit?: number;
  };

  // Webhook configuration for this connection
  webhookConfig?: {
    // Unique webhook token for this connection
    webhookToken: string;

    // Webhook URL (generated by system)
    webhookUrl: string;

    // Events this connection listens to
    events: string[];

    // Webhook status
    verified: boolean;

    // When webhook was last verified
    verifiedAt?: Date;
  };

  // RBAC: Users who have access to this connection
  accessControl?: {
    userId: string;
    role: 'viewer' | 'operator' | 'admin'; // Connection-specific roles
    grantedAt: Date;
    grantedBy: string;
  }[];

  // Auto-sync configuration
  autoSync?: {
    enabled: boolean;
    interval?: number; // milliseconds
    lastSyncAt?: Date;
    nextSyncAt?: Date;
    syncErrors?: string[];
  };

  // Whether connection is read-only (no write operations)
  isReadOnly?: boolean;

  // Expiration date (for tokens that expire)
  expiresAt?: Date;

  // Tags for categorization
  tags?: string[];

  // Internal notes
  notes?: {
    note: string;
    authorId: string;
    createdAt: Date;
  }[];

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

/**
 * ProviderConnection Schema
 */
const ProviderConnectionSchema = new Schema<IProviderConnection>(
  {
    providerId: {
      type: String,
      required: true,
      index: true,
    },
    tenantId: {
      type: Schema.Types.ObjectId,
      required: true,
      ref: 'Tenant',
      index: true,
    },
    createdBy: {
      type: String,
      required: true,
    },
    displayName: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      enum: ['active', 'inactive', 'error', 'pending_auth', 'expired'],
      default: 'inactive',
      index: true,
    },
    credentials: {
      encrypted: {
        type: String,
        required: true,
      },
      algorithm: {
        type: String,
        default: 'aes-256-gcm',
      },
      iv: {
        type: String,
        required: true,
      },
      authTag: {
        type: String,
        required: true,
      },
    },
    config: {
      type: Schema.Types.Mixed,
      required: true,
    },
    metadata: {
      type: Schema.Types.Mixed,
    },
    lastAuthenticatedAt: Date,
    lastAuthFailureAt: Date,
    failureCount: {
      type: Number,
      default: 0,
    },
    maxFailureThreshold: {
      type: Number,
      default: 5,
    },
    disabledUntil: Date,
    stats: {
      totalRequests: { type: Number, default: 0 },
      totalErrors: { type: Number, default: 0 },
      averageResponseTime: Number,
      lastUsedAt: Date,
      quotaUsed: Number,
      quotaLimit: Number,
    },
    webhookConfig: {
      webhookToken: String,
      webhookUrl: String,
      events: [String],
      verified: { type: Boolean, default: false },
      verifiedAt: Date,
    },
    accessControl: [
      {
        userId: String,
        role: {
          type: String,
          enum: ['viewer', 'operator', 'admin'],
        },
        grantedAt: { type: Date, default: Date.now },
        grantedBy: String,
        _id: false,
      },
    ],
    autoSync: {
      enabled: { type: Boolean, default: false },
      interval: Number,
      lastSyncAt: Date,
      nextSyncAt: Date,
      syncErrors: [String],
    },
    isReadOnly: {
      type: Boolean,
      default: false,
    },
    expiresAt: Date,
    tags: [String],
    notes: [
      {
        note: String,
        authorId: String,
        createdAt: { type: Date, default: Date.now },
        _id: false,
      },
    ],
  },
  {
    timestamps: true,
  },
);

// Compound index for unique connection per tenant per provider
ProviderConnectionSchema.index({ tenantId: 1, providerId: 1 });

// Indexes for performance
ProviderConnectionSchema.index({ status: 1, tenantId: 1 });
ProviderConnectionSchema.index({ createdAt: -1 });
ProviderConnectionSchema.index({ tags: 1 });
ProviderConnectionSchema.index({ 'accessControl.userId': 1 });
ProviderConnectionSchema.index({ 'webhookConfig.webhookToken': 1 });

// Virtual: is connection expired
ProviderConnectionSchema.virtual('isExpired').get(function () {
  if (!this.expiresAt) return false;
  return new Date() > this.expiresAt;
});

// Virtual: is connection disabled due to failures
ProviderConnectionSchema.virtual('isDisabled').get(function () {
  if (!this.disabledUntil) return false;
  return new Date() < this.disabledUntil;
});

// Virtual: can connection be used
ProviderConnectionSchema.virtual('canBeUsed').get(function () {
  return (
    this.status === 'active' &&
    !this.isExpired &&
    !this.isDisabled
  );
});

/**
 * Create or get ProviderConnection model
 */
export const ProviderConnection =
  mongoose.models.ProviderConnection ||
  mongoose.model<IProviderConnection>('ProviderConnection', ProviderConnectionSchema);

export default ProviderConnection;
